local tips={
    "哦哦，哦哦哦！",
    "感觉……不如……Techmino……",
    "Push是什么 不知道",
    "卖弱的一律当5pps处理",
    "狗都sub30了",
    "吃四碗，爽！",
    "哇袄！！！",
    "Lua天下第一！",
    "海兰就是个彩笔打块的，懂什么代码",
    "Bad argument #6623:Attempt to compare number with nil",
    "我是一条凑数tip",
    "你说得对，但是……",
    "打SDPC不接DPC，那我缺的这个spike这块谁给我补啊",
    "这是海兰，既没实力又不可爱，只会在tip里口嗨",
    "反正我不是第一个往方块游戏里加tip的",
    "A Project by TEAM BLANKER",
    "游戏的生日？2023年暑假的时候开发的，就定在8月14日吧",
    "Z酱锐评：“抄铁壳抄的挺到位的”",
    "Carbon Fibre方块皮肤的灵感来自于碳纤维贴纸魔方",
    "Aquamino特色推箱子",
    "虽然名字是水，但海兰可不保证每个模式都和水有关系",
    "本游戏的SRS经过修改，I旋对称，并且加入了180°踢墙"
}
return tips